/**
 * Created by kwame on 10/9/16.
 */


 const  REQUEST_STATE={
  REQUEST_INIT:"REQUEST_INIT",
  REQUEST_WAIT:"REQUEST_WAIT",
  REQUEST_TIMEOUT:"REQUEST_TIMEOUT",
  REQUEST_ERROR:"REQUEST_ERROR",
  REQUEST_OK:"REQUEST_OK"
};
export default REQUEST_STATE;
