const LOCAL_EVENT = {
  WEBSOCKET_OPEN: 'WEBSOCKET_OPEN',
  WEBSOCKET_CLOSE: 'WEBSOCKET_CLOSE',
  WEBSOCKET_ERROR: 'WEBSOCKET_ERROR',
  WEBSOCKET_MESSAGE: 'WEBSOCKET_MESSAGE',
  WEBSOCKET_BUILD: 'WEBSOCKET_BUILD',
  WEBSOCKET_TIMEOUT:'WEBSOCKET_TIMEOUT',

  TEST_REDUX:'TEST_REDUX',

};
export default LOCAL_EVENT;
