const REMOTE_MESSAGE_TYPE = {
  WEBSOCKET_OPEN:'WEBSOCKET_OPEN',
  WEBSOCKET_CLOSE:'WEBSOCKET_CLOSE',
  WEBSOCKET_ERROR:'WEBSOCKET_ERROR',
  WEBSOCKET_MESSAGE:'WEBSOCKET_MESSAGE',


};
export default REMOTE_MESSAGE_TYPE;
